- name: 'Set Xfce4 power-manager settings'
  become_user: '{{ xfce4_role_user.name }}'
  community.general.xfconf:
    channel: 'xfce4-power-manager'
    property: '/xfce4-power-manager/{{ item.property }}'
    value_type: '{{ item.value_type }}'
    value: '{{ item.value }}'
  environment:
    DBUS_SESSION_BUS_ADDRESS: 'unix:path=/run/user/{{ xfce4_role_user.uid }}/bus'
  loop: '{{ xfce4_power_manager_settings }}'
