terraform_apt_repository_signing_key: 'https://apt.releases.hashicorp.com/gpg'
terraform_apt_repository_url: 'https://apt.releases.hashicorp.com'
terraform_apt_repository_options: 'bookworm main'

terraform_packages:
  - 'terraform'
