##################################################
###################### Xfce4 #####################
##################################################

xfce4_base_packages:
  - 'xfce4-helpers'
  - 'xfce4-session'
  - 'xfce4-settings'
  - 'xfconf'

xfce4_helper_packages:
  - 'xcape'
  - 'xfce4-clipman'
  - 'xfce4-taskmanager'
