---
- name: 'Get DevToys latest release version'
  ansible.builtin.uri:
    url: 'https://api.github.com/repos/{{ devtoys_github_repository }}/releases'
    return_content: true
  register: 'devtoys_releases'

- name: 'Get the first DevToys prerelease tag_name'
  set_fact:
    devtoys_version: "{{ (devtoys_releases.content | from_json | json_query('[?prerelease == `true`].tag_name'))[0] }}"

- name: 'Create DevToys dotfiles work directory'
  ansible.builtin.file:
    path: '{{ devtoys_ansible_work_path }}'
    state: directory
    owner: 'root'
    group: 'root'
    mode: '0775'

- name: 'Download DevToys latest release'
  ansible.builtin.get_url:
    url: 'https://github.com/{{ devtoys_github_repository }}/releases/download/{{ devtoys_version }}/devtoys_linux_x64.deb'
    dest: '{{ devtoys_ansible_work_path }}/devtoys_x64.deb'
    mode: '0660'
    force: true

- name: 'Install DevToys'
  ansible.builtin.apt:
    deb: '{{ devtoys_ansible_work_path }}/devtoys_x64.deb'
