---
- name: 'Install OBS Studio required packages'
  ansible.builtin.apt:
    name: '{{ obs_studio_required_packages }}'
    state: present
    install_recommends: false

- name: 'Install OBS Studio'
  community.general.flatpak:
    name: '{{ obs_studio_flathub_id }}'
    state: present
