---
- name: 'Add Trivy repository signing key'
  ansible.builtin.get_url:
    url: '{{ trivy_apt_repository_signing_key }}'
    dest: '/usr/share/keyrings/trivy.key'
    owner: 'root'
    group: 'root'
    mode: '0644'
    force: true

- name: 'Add Trivy repository to apt'
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/trivy.key] {{ trivy_apt_repository_url }} {{ trivy_apt_repository_options }}'
    state: present

- name: 'Update APT repository cache'
  ansible.builtin.apt:
    update_cache: true

- name: 'Install Trivy'
  ansible.builtin.apt:
    name: '{{ trivy_packages }}'
    state: present
    install_recommends: false
