---
- name: 'Install Xfce4 base packages'
  ansible.builtin.apt:
    name: '{{ xfce4_base_packages }}'
    state: present
    install_recommends: false

- name: 'Create Xfce4 configuration directory in config folder'
  ansible.builtin.file:
    path: '{{ xfce4_role_user.home }}/.config/xfce4'
    state: directory
    owner: '{{ xfce4_role_user.name }}'
    group: '{{ xfce4_role_user.name }}'
    mode: '0770'

- name: 'Create Xfce4 configuration directory in local folder'
  ansible.builtin.file:
    path: '{{ xfce4_role_user.home }}/.local/share/xfce4'
    state: directory
    owner: '{{ xfce4_role_user.name }}'
    group: '{{ xfce4_role_user.name }}'
    mode: '0770'
