---
- name: 'Install network-manager'
  ansible.builtin.apt:
    name: '{{ network_manager_packages }}'
    state: present
    install_recommends: false

- name: 'Create /etc/NetworkManager directory'
  ansible.builtin.file:
    path: '/etc/NetworkManager'
    state: directory
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Configure /etc/NetworkManager/NetworkManager.conf file'
  ansible.builtin.copy:
    dest: '/etc/NetworkManager/NetworkManager.conf'
    content: |
      {{ network_manager_conf_file_content }}
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Disable the networking service'
  ansible.builtin.systemd_service:
    name: 'networking.service'
    enabled: false

- name: 'Enable the NetworkManager service'
  ansible.builtin.systemd_service:
    name: 'NetworkManager.service'
    enabled: true

- name: 'Copy NetworkManager connection files'
  ansible.builtin.copy:
    src: '{{ network_manager_connection_shared_files_path }}/{{ item }}'
    dest: '/etc/NetworkManager/system-connections/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: '0600'
  loop: '{{ network_manager_connection_files }}'
