ssh_role_user_name: '{{ users.admin.name }}'

# This variable is sensitive, so it must be declared in an ansible-vault
# Example:
#
# ssh_private_keys:
#   id_ed25519: |
#     -----BEGIN OPENSSH PRIVATE KEY-----
#     .
#     .
#     .
#     -----END OPENSSH PRIVATE KEY-----

ssh_private_keys: {}
