---
- name: 'Delete Ansible work directory'
  ansible.builtin.file:
    path: '{{ ansible_work_path }}'
    state: absent

- name: 'Remove useless packages from APT cache'
  ansible.builtin.apt:
    autoclean: true

- name: 'Remove package dependencies that are no longer required from APT'
  ansible.builtin.apt:
    autoremove: true
