apt_sources_file_content: |
  deb http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware
  deb-src http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware

  deb http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware
  deb-src http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware

  # bookworm-updates, to get updates before a point release is made;
  # see https://www.debian.org/doc/manuals/debian-reference/ch02.en.html # _updates_and_backports
  deb http://deb.debian.org/debian/ bookworm-updates main contrib non-free non-free-firmware
  deb-src http://deb.debian.org/debian/ bookworm-updates main contrib non-free non-free-firmware

apt_remove_packages: []

apt_install_base_packages:
  - 'acl'
  - 'apt-transport-https'
  - 'build-essential'
  - 'curl'
  - 'git'
  - 'gvfs-backends'
  - 'libsecret-1-0'
  - 'python3'
  - 'software-properties-common'
  - 'wget'

apt_install_linux_kernel_headers: true

apt_install_packages:
  - 'fzf'
  - 'htop'
  - 'pipx'
  - 'python3-requests'
  - 'rename'
  - 'rsync'
  - 'rsyslog'
  - 'sshpass'
  - 'tree'
