---
- name: 'Get user info for Xfce4 role'
  register: 'xfce4_role_user'
  ansible.builtin.user:
    name: '{{ xfce4_role_user_name }}'

- name: 'Install desktop-base'
  ansible.builtin.apt:
    name: 'desktop-base'
    state: present
    install_recommends: false

- name: 'Install & configure Xfce4'
  ansible.builtin.include_tasks: 'xfce4/main.yaml'

- name: 'Install & configure Xfce4 theme'
  ansible.builtin.include_tasks: 'theme/main.yaml'

- name: 'Install & configure Xfwm4'
  ansible.builtin.include_tasks: 'xfwm4/main.yaml'

- name: 'Install & configure Xfce4 notifications'
  ansible.builtin.include_tasks: 'notifications/main.yaml'

- name: 'Install & configure Xfce4 panels'
  ansible.builtin.include_tasks: 'panels/main.yaml'

- name: 'Install & configure gnome-keyring'
  ansible.builtin.include_tasks: 'gnome-keyring/main.yaml'

- name: 'Install & configure Ristretto Image Viewer'
  ansible.builtin.include_tasks: 'ristretto/main.yaml'

- name: 'Install & configure Xfce4 screenshooter'
  ansible.builtin.include_tasks: 'screenshooter/main.yaml'

- name: 'Install & configure Mousepad'
  ansible.builtin.include_tasks: 'mousepad/main.yaml'

- name: 'Install & configure Thunar'
  ansible.builtin.include_tasks: 'thunar/main.yaml'

- name: 'Install & configure Tumbler'
  ansible.builtin.include_tasks: 'tumbler/main.yaml'

- name: 'Install & configure Xfce4 power-manager'
  ansible.builtin.include_tasks: 'power-manager/main.yaml'
