---
- name: 'Copy SSH config template file'
  ansible.builtin.copy:
    content: |
      {% for item in ssh_private_keys %}
      IdentityFile '{{ ssh_role_user.home }}/.ssh/{{ item }}'
      {% endfor %}
    dest: '{{ ssh_ansible_work_path }}/config.j2'
    owner: '{{ ssh_role_user.name }}'
    group: '{{ ssh_role_user.name }}'
    mode: '0660'

- name: 'Create SSH directory'
  ansible.builtin.file:
    path: '{{ ssh_role_user.home }}/.ssh'
    state: directory
    owner: '{{ ssh_role_user.name }}'
    group: '{{ ssh_role_user.name }}'
    mode: '0770'

- name: 'Create ~/.ssh/config file'
  ansible.builtin.copy:
    src: '{{ ssh_ansible_work_path }}/config.j2'
    dest: '{{ ssh_role_user.home }}/.ssh/config'
    owner: '{{ ssh_role_user.name }}'
    group: '{{ ssh_role_user.name }}'
    mode: '0600'

- name: 'Copy SSH private keys'
  ansible.builtin.copy:
    content: '{{ item.value }}'
    dest: '{{ ssh_role_user.home }}/.ssh/{{ item.key }}'
    owner: '{{ ssh_role_user.name }}'
    group: '{{ ssh_role_user.name }}'
    mode: '0600'
  loop: '{{ ssh_private_keys | dict2items }}'
  no_log: true
