helm_plugins:
  - name: 'diff'
    url: 'https://github.com/databus23/helm-diff'
  - name: 'helm-git'
    url: 'https://github.com/aslafy-z/helm-git'
  - name: 'secrets'
    url: 'https://github.com/jkroepke/helm-secrets'
  - name: 's3'
    url: 'https://github.com/hypnoglow/helm-s3'

