---
- name: 'Install Flatpak required packages'
  ansible.builtin.apt:
    name: '{{ flatpak_required_packages }}'
    state: present
    install_recommends: false

- name: 'Install Flatpak using APT'
  ansible.builtin.apt:
    name: 'flatpak'
    state: present
    install_recommends: false

- name: 'Add Flathub repository support in Flatpak'
  community.general.flatpak_remote:
    name: 'flathub'
    state: present
    flatpakrepo_url: '{{ flathub_repository_url }}'
