---
- name: 'Install KWrite packages'
  ansible.builtin.apt:
    name: '{{ kde_plasma_kwrite_packages }}'
    state: present
    install_recommends: false

- name: 'Install spellcheck dictionaries for KWrite'
  ansible.builtin.apt:
    name: '{{ kde_plasma_kwrite_spellcheck_support_packages }}'
    state: present
    install_recommends: false

- name: 'Install spellcheck dictionaries for KWrite'
  ansible.builtin.apt:
    name: '{{ kde_plasma_kwrite_spellcheck_dictionaries }}'
    state: present
    install_recommends: false
