---
- name: 'Create kubernetes contexts directory'
  ansible.builtin.file:
    path: '{{ kubectl_role_user.home }}/.kube'
    state: directory
    owner: '{{ kubectl_role_user.name }}'
    group: '{{ kubectl_role_user.name }}'
    mode: '0770'

- name: 'Copy default kubernetes context file'
  ansible.builtin.copy:
    src: '{{ kubectl_role_files_path }}/default.conf'
    dest: '{{ kubectl_role_user.home }}/.kube/conf'
    owner: '{{ kubectl_role_user.name }}'
    group: '{{ kubectl_role_user.name }}'
    mode: '0660'

- name: 'Copy kubernetes context files'
  ansible.builtin.copy:
    src: '{{ kubectl_kubecontext_shared_files_path }}/{{ item }}'
    dest: '{{ kubectl_role_user.home }}/.kube/{{ item }}'
    owner: '{{ kubectl_role_user.name }}'
    group: '{{ kubectl_role_user.name }}'
    mode: '0660'
  loop: '{{ kubectl_context_files }}'
