---
- name: 'Install UFW'
  ansible.builtin.apt:
    name: 'ufw'
    state: present
    install_recommends: false

- name: 'Reset UFW rules'
  community.general.ufw:
    state: reset

- name: 'Configure UFW to allow outgoing traffic'
  community.general.ufw:
    direction: out
    rule: allow

- name: 'Configure UFW to allow incoming traffic from allowed ips'
  community.general.ufw:
    direction: in
    rule: allow
    from_ip: '{{ item.from_ip }}'
    to_port: '{{ item.to_port }}'
  loop: '{{ firewall_allow_incoming }}'

- name: 'Configure UFW to reject incoming traffic'
  community.general.ufw:
    direction: in
    rule: reject
    log: true

- name: 'Enable UFW logging'
  community.general.ufw:
    logging: 'on'

- name: 'Enable UFW'
  community.general.ufw:
    state: enabled
