hostname: 'WORKSTATION'

users:
  admin:
    name: 'tux'
    uid: 1000
    has_sudo_privileges: true
    ssh_authorized_keys: []

# This variable is sensitive, so it must be declared in an ansible-vault
user_passwords:
  tux: '123456'
