##################################################
################### KDE Plasma ###################
##################################################

kde_plasma_base_packages:
  - 'plasma-desktop'
  - 'plasma-workspace-wayland'

kde_plasma_setting_packages:
  - 'bluedevil'
  - 'kde-config-screenlocker'
  - 'kscreen'
  - 'plasma-nm'
  - 'powerdevil'
  - 'systemsettings'

##################################################
##################### KWallet ####################
##################################################

kde_plasma_kwallet_packages:
  - 'libkf5wallet-bin'

kde_plasma_kwallet_pam_enabled: true

kde_plasma_kwallet_pam_packages:
  - 'libpam-kwallet5'

##################################################
##################### Dolphin ####################
##################################################

kde_plasma_dolphin_packages:
  - 'dolphin'
  - 'dolphin-plugins'

##################################################
##################### KWrite #####################
##################################################

kde_plasma_kwrite_packages:
  - 'kwrite'

kde_plasma_kwrite_spellcheck_support_packages:
  - 'sonnet-plugins'

kde_plasma_kwrite_spellcheck_dictionaries:
  - 'hunspell-en-us'

##################################################
###################### Elisa #####################
##################################################

kde_plasma_elisa_packages:
  - 'elisa'

##################################################
############ KDE Plasma Screenshooter ############
##################################################

kde_plasma_screenshooter_packages:
  - 'kde-spectacle'
