gpg_role_user_name: '{{ users.admin.name }}'

gpg_packages:
  - 'gpg'

# This variable is sensitive, so it must be declared in an ansible-vault
# Example:
#
# gpg_keys:
#   private_key: |
#     -----BEGIN PGP PRIVATE KEY BLOCK-----
#     .
#     .
#     .
#     -----END PGP PRIVATE KEY BLOCK-----
#
gpg_keys: {}
