---
- name: 'Ensure locale exists'
  community.general.locale_gen:
    name: '{{ base_locale }}.UTF-8'
    state: present

- name: 'Configure locale'
  ansible.builtin.copy:
    dest: '/etc/default/locale'
    content: |
      LANG={{ base_locale }}.UTF-8
      LC_NUMERIC={{ base_locale }}.UTF-8
      LC_TIME={{ base_locale }}.UTF-8
      LC_MONETARY={{ base_locale }}.UTF-8
      LC_PAPER={{ base_locale }}.UTF-8
      LC_NAME={{ base_locale }}.UTF-8
      LC_ADDRESS={{ base_locale }}.UTF-8
      LC_TELEPHONE={{ base_locale }}.UTF-8
      LC_MEASUREMENT={{ base_locale }}.UTF-8
      LC_IDENTIFICATION={{ base_locale }}.UTF-8
      LANGUAGE={{ base_locale }}
    owner: 'root'
    group: 'root'
    mode: '0644'
