---
- name: 'Get user info for Vim role'
  register: 'vim_role_user'
  ansible.builtin.user:
    name: '{{ vim_role_user_name }}'

- name: 'Install Vim'
  ansible.builtin.apt:
    name: 'vim'
    state: present
    install_recommends: false

- name: 'Configure Vim'
  ansible.builtin.copy:
    src: '{{ vim_shared_files_path }}/{{ vim_config_filename }}'
    dest: '{{ vim_role_user.home }}/.vimrc'
    owner: '{{ vim_role_user.name }}'
    group: '{{ vim_role_user.name }}'
    mode: '0660'
