---
- name: 'Create Rustup role work directory'
  ansible.builtin.file:
    path: '{{ rust_lang_ansible_work_path }}'
    state: directory
    owner: 'root'
    group: 'root'
    mode: '0775'

- name: 'Download the latest rustup-init binary'
  ansible.builtin.get_url:
    url: '{{ rust_lang_rustup_download_path }}'
    dest: '{{ rust_lang_ansible_work_path }}/rustup-init'
    owner: 'root'
    group: 'root'
    mode: '0715'
    force: true

- name: 'Install Rust'
  ansible.builtin.shell: '{{ rust_lang_ansible_work_path }}/rustup-init --default-toolchain stable --profile default --no-modify-path -y'
  environment:
    RUSTUP_HOME: '/usr/local/rustup'
    CARGO_HOME: '/usr/local/cargo'
